---
title: Lightning Flash Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: gai@lightningflashstudio.com
description: Photos & Scribbles
url: https://lightningflashstudio.com
baseurl: ''
pinterest_username: theRealLfs
tumblr_username: lightningflashstudio
github_username: LightningFlashStudio
discus_shortname: lightningflashstudio-com
share: true
owner:
  name: Kornell Gai
  avatar: avatar.png
  favicon: favicon.ico
  info: photography & tech website
comments:
  provider: disqus
  disqus:
    short_name: lightningflashstudio-com
nav:
- GALLERY: https://lightningflashstudio.com/gallery/
- JOURNAL: https://lightningflashstudio.com/journal/
- ABOUT: https://lightningflashstudio.com/about/
translations:
  permalink: "/404.html"
destination: "./_site"
port: 4000
markdown: kramdown
highlighter: rouge
permalink: "/journal/:title/"
paginate: 5
paginate_path: "/journal/page:num/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
google_analytics: UA-108714446-1
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-avatar
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
sitemap:
  file: "/sitemap.xml"
  exclude:
  - "/atom.xml"
  - "/feed.xml"
  - "/feed/index.xml"
  include_posts:
  - "/writing/"
  change_frequency_name: change_frequency
  priority_name: priority
